### ISSUE TITLE
Error while initial setup

### ISSUE THREAD

**Issue by medampudi** [growyourlist/growyourlist#1] opened 2020-03-08 21:48 UTC
![Screenshot 2020-03-09 at 2 03 41 AM](https://user-images.githubusercontent.com/649199/76171724-81ecaa80-61b4-11ea-9920-d2c2a8a9604d.png)
Have a look at this issue i got while installing the system. Can you please help me solve it.

**Comment by gyl-dev** [comment] 2020-04-01 11:41
Thank you very much for having a look at growyourlist, you're the first!
We've done a lot of work on it the past few weeks and have probably fixed the issue you were facing.
Please try:

1. Deleting resources created by the script (resources starting with 'Gyl' in DynamoDB, IAM users and policies, and lambda functions). You can try `npx growyourlist destruct` to do this, but please be only do this if you are using a test aws account. Don't want to accidentally delete anything important! You can review the code that will be run here: [gyl-uninstall.js](https://github.com/growyourlist/gyl-init/blob/master/src/gyl-uninstall.js)
1. Going into an empty directory and running `npx growyourlist setup` again. The latest version should work.

Let us know if that resolves your issue! Thanks!

**Comment by dawidholka** [comment] 2020-09-08 20:07
> Thank you very much for having a look at growyourlist, you're the first!
> We've done a lot of work on it the past few weeks and have probably fixed the issue you were facing.
> Please try:
> 
> 1. Deleting resources created by the script (resources starting with 'Gyl' in DynamoDB, IAM users and policies, and lambda functions). You can try `npx growyourlist destruct` to do this, but please be only do this if you are using a test aws account. Don't want to accidentally delete anything important! You can review the code that will be run here: [gyl-uninstall.js](https://github.com/growyourlist/gyl-init/blob/master/src/gyl-uninstall.js)
> 2. Going into an empty directory and running `npx growyourlist setup` again. The latest version should work.
> 
> Let us know if that resolves your issue! Thanks!

Hello,
I'm trying to install GYL but having the same problem as the author of the issue.
I am following your instructions, but keep getting the same error :(

**Comment by gyl-dev** [comment] 2020-09-08 20:10
@dawidholka thanks for reporting that this is still an issue. Which OS did you use? I'll try and run the setup in the same environment and see what happens.

**Comment by dawidholka** [comment] 2020-09-08 20:11
> @dawidholka thanks for reporting that this is still an issue. Which OS did you use? I'll try and run the setup in the same environment and see what happens.

I am using MacOS 10.15.6, but i also tried at Ubuntu 20.04 with the same result.

**Comment by gyl-dev** [comment] 2020-09-08 20:12
Interesting, I've not tried it on either of those yet - I'll give it a go and let you know if I can find a fix for it 🙂

**Comment by dawidholka** [comment] 2020-09-08 20:15
Could it be that I gave the wrong policy permissions to IAM user?

**Comment by gyl-dev** [comment] 2020-09-08 20:22
I don't believe so - it looks like a temporary local directory containing a copy of all the code for the lambda functions for the mailing list fails to get created. So this should happen just before any IAM permissions checks (but there may be other permission issues waiting just around the corner if the policy doesn't cover all the permissions required by the script).

**Comment by gyl-dev** [comment] 2020-09-08 21:05
I found the issue and I'm writing a fix for it now. It split the path it was checking up by / causing the first part of the path to be an empty string - failing the 'does it exist' check. I'm adding to code to handle this situation now.

**Comment by gyl-dev** [comment] 2020-09-08 22:46
@dawidholka I believe the issue is fixed now; you can retry the setup with:
`npx growyourlist@0.0.21 destruct`
`npx growyourlist@0.0.21 setup`
The appended version 0.0.21 will ensure you get the version with the fix in it. For people reading this in the future: the version shouldn't be needed, the latest version should work.

**Comment by dawidholka** [comment] 2020-09-09 07:19
@gyl-dev 
Thank you, it's working now. :)

**Comment by gyl-dev** [comment] 2020-09-09 07:53
@dawidholka great to hear it's working. Feel free to raise more issues if you come across any other problems or things that could be improved 🙂

**Closed** 2020-09-09 07:54 UTC
